# Generated by Django 4.0.8 on 2024-01-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_upload_file_alter_uploadvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Bachloar', 'Bakalavr diplomi'), ('Master', 'Magistr diplomi')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First', 'Birinchi'), ('Second', 'Ikkinchi'), ('Third', 'Uchinchi')], max_length=200),
        ),
    ]
