# Generated by Django 4.0.8 on 2024-01-30 18:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_figure_alter_quiz_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Tanlov', 'verbose_name_plural': 'Tanlovlar'},
        ),
        migrations.AlterModelOptions(
            name='essayquestion',
            options={'verbose_name': 'Insho uslubidagi savol', 'verbose_name_plural': 'Insho uslubidagi savollar'},
        ),
        migrations.AlterModelOptions(
            name='mcquestion',
            options={'verbose_name': "Ko'p tanlovli savol", 'verbose_name_plural': "Ko'p tanlovli savollar"},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Foydalanuvchi taraqqiyoti', 'verbose_name_plural': 'Foydalanuvchi taraqqiyoti qaydlari'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Viktorina', 'verbose_name_plural': 'Viktorinalar'},
        ),
        migrations.AlterModelOptions(
            name='sitting',
            options={'permissions': (('view_sittings', "Tugallangan imtihonlarni ko'rish mumkin."),)},
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(help_text="Ko'rsatmoqchi bo'lgan tanlov matnini kiriting", max_length=1000, verbose_name='Tarkib'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=False, help_text="Bu to'g'ri javobmi?", verbose_name='Tarkib'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.mcquestion', verbose_name='Viktorena'),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='choice_order',
            field=models.CharField(blank=True, choices=[('content', "Tartib bo'yicha"), ('random', 'Aralashtirish'), ('none', 'Nomalum')], help_text="Ushbu bo'limda siz savol qay tarzda foydalanuvchilarga uzatilishini taminlaysiz!", max_length=30, null=True, verbose_name='Savol turinini tanlang'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(help_text="Ko'rinishi kerak bo'lgan savol matnini kiriting:", max_length=1000, verbose_name='Savol kiriting'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text="Majburiy emas. Ammo savolingiz anchayin murakkab bo'lsa ushbu bo'limdan foydalanishingiz foydalanuvchilarga anchayin ast qotishi mumkin", max_length=2000, verbose_name='Savol haqida'),
        ),
        migrations.AlterField(
            model_name='question',
            name='figure',
            field=models.ImageField(blank=True, help_text="Agar kerak bo'lsa, savol uchun rasm qo'shing.", null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Rasm yuklashingiz mumkin:'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answers_at_end',
            field=models.BooleanField(default=False, help_text="To'g'ri javob savoldan keyin ko'rsatilmaydi. Javoblar oxirida ko'rsatiladi.", verbose_name='Javoblar oxirida'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.TextField(blank=True, choices=[('assignment', 'Tajriba oshirish'), ('exam', 'Oraliq testi'), ('practice', 'Amaliyot test')]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, help_text='Viktorinaning batafsil tavsifi.', verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='draft',
            field=models.BooleanField(blank=True, default=False, help_text="Ha bo'lsa, viktorina viktorina ro'yxatida ko'rsatilmaydi va uni faqat viktorinalarni tahrir qila oladigan foydalanuvchilar olishi mumkin.", verbose_name='Qoralama'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exam_paper',
            field=models.BooleanField(default=False, help_text="Ha bo'lsa, foydalanuvchining har bir urinishining natijasi saqlanadi. Belgilash foydali bo'lishi mumkin.", verbose_name="Imtihon qog'ozi"),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_mark',
            field=models.SmallIntegerField(blank=True, default=50, help_text="Imtihondan o'tish uchun talab qilinadigan foiz.", validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Max ball'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='random_order',
            field=models.BooleanField(default=False, help_text="Savollarni tasodifiy tartibda yoki belgilangan tartibda ko'rsatilsimni?", verbose_name='Tasodifiy testlar'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='single_attempt',
            field=models.BooleanField(default=False, help_text="Ha bo'lsa, foydalanuvchining faqat bitta urinishiga ruxsat beriladi.", verbose_name='Yagona urinish'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Bajarildi'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='current_score',
            field=models.IntegerField(verbose_name='Joriy ball'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxiri'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='incorrect_questions',
            field=models.CharField(blank=True, max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name="Noto'g'ri savollar"),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='question_list',
            field=models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name="Savollar ro'yxati"),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='question_order',
            field=models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Savol berish tartibi'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Boshlash'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user_answers',
            field=models.TextField(blank=True, default='{}', verbose_name='Foydalanuvchi javoblari'),
        ),
    ]
