# Generated by Django 4.0.8 on 2024-01-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_department_student_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='relation_ship',
            field=models.TextField(blank=True, choices=[('Father', 'Ota'), ('Mother', 'Ona'), ('Brother', 'Aka'), ('Sister', 'Singil'), ('Grand mother', 'Katta aka'), ('Grand father', 'Katta opa'), ('Other', 'Boshqa')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Bachloar', 'Bakalavr diplomi'), ('Master', 'Magistr diplomi')], max_length=25, null=True),
        ),
    ]
