# Generated by Django 4.2.9 on 2024-01-11 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistoryBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name="ChatHistory_backup",
        ),
        migrations.AddField(
            model_name="chathistory",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
