# Generated by Django 4.2.9 on 2024-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_chathistorybackup_delete_chathistory_backup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="username",
            field=models.CharField(default="testUsername", max_length=200),
            preserve_default=False,
        ),
    ]
