# Generated by Django 4.2.9 on 2024-01-12 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_chathistory_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("user", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="chathistorybackup",
            name="username",
            field=models.CharField(default="testUsername", max_length=200),
            preserve_default=False,
        ),
    ]
